"""Add image and video link columns to question tables

Revision ID: 37c612a01e8c
Revises: 47ba2939ea04
Create Date: 2025-09-12 17:54:09.071765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37c612a01e8c'
down_revision: Union[str, Sequence[str], None] = '47ba2939ea04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alembic_version')
    op.add_column('model_papers', sa.Column('question_image_url', sa.String(), nullable=True), schema='sources')
    op.add_column('model_papers', sa.Column('answer_image_url', sa.String(), nullable=True), schema='sources')
    op.add_column('model_papers', sa.Column('youtube_link', sa.String(), nullable=True), schema='sources')
    op.add_column('past_papers', sa.Column('question_image_url', sa.String(), nullable=True), schema='sources')
    op.add_column('past_papers', sa.Column('answer_image_url', sa.String(), nullable=True), schema='sources')
    op.add_column('past_papers', sa.Column('youtube_link', sa.String(), nullable=True), schema='sources')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('past_papers', 'youtube_link', schema='sources')
    op.drop_column('past_papers', 'answer_image_url', schema='sources')
    op.drop_column('past_papers', 'question_image_url', schema='sources')
    op.drop_column('model_papers', 'youtube_link', schema='sources')
    op.drop_column('model_papers', 'answer_image_url', schema='sources')
    op.drop_column('model_papers', 'question_image_url', schema='sources')
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    # ### end Alembic commands ###
