"""Add media URLs to messages table

Revision ID: 9c87c0e648f5
Revises: 37c612a01e8c
Create Date: 2025-09-13 00:40:14.187309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c87c0e648f5'
down_revision: Union[str, Sequence[str], None] = '37c612a01e8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('question_image_url', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('answer_image_url', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('youtube_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'youtube_link')
    op.drop_column('messages', 'answer_image_url')
    op.drop_column('messages', 'question_image_url')
    # ### end Alembic commands ###
