"""Add sources schema and full text search

Revision ID: 47ba2939ea04
Revises: e8af7c540676
Create Date: 2025-08-25 19:21:03.833187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47ba2939ea04'
down_revision: Union[str, Sequence[str], None] = 'e8af7c540676'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='sources'
    )
    op.create_table('model_papers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('paper_name', sa.String(), nullable=False),
    sa.Column('question_type', sa.Enum('mcq', 'structure', 'essay', name='question_type_enum', schema='sources'), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('question_unit', sa.String(), nullable=True),
    sa.Column('question_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('answer_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('relevant_theory', sa.Text(), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['sources.subjects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sources'
    )
    op.create_index('ix_sources_model_papers_search_vector', 'model_papers', ['search_vector'], unique=False, schema='sources', postgresql_using='gin')
    op.create_table('past_papers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.Enum('mcq', 'structure', 'essay', name='question_type_enum', schema='sources'), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('question_unit', sa.String(), nullable=True),
    sa.Column('question_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('answer_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('relevant_theory', sa.Text(), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['sources.subjects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sources'
    )
    op.create_index('ix_sources_past_papers_search_vector', 'past_papers', ['search_vector'], unique=False, schema='sources', postgresql_using='gin')
    op.create_table('theories',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('main_heading', sa.String(), nullable=False),
    sa.Column('sub_heading', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['sources.subjects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sources'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('theories', schema='sources')
    op.drop_index('ix_sources_past_papers_search_vector', table_name='past_papers', schema='sources', postgresql_using='gin')
    op.drop_table('past_papers', schema='sources')
    op.drop_index('ix_sources_model_papers_search_vector', table_name='model_papers', schema='sources', postgresql_using='gin')
    op.drop_table('model_papers', schema='sources')
    op.drop_table('subjects', schema='sources')
    # ### end Alembic commands ###
